import Head from 'next/head'
import About from '../components/About'
import Projects from '../components/Projects'
import UpperSec from '../components/UpperSec'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Atul Tripathi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <UpperSec />
      <div id="about">
        <About />
      </div>
      <div id="projects">
        <Projects/>
      </div>

    </div>
  )
}
